const TIMER_KICK_OFF = 'TIMER_KICK_OFF';
const TIMER_ADD_SECOND = 'TIMER_ADD_SECOND';
const TIMER_TIME_OFF = 'TIMER_TIME_OFF';
const TIMER_TIME_ON = 'TIMER_TIME_ON';
const TIMER_END = 'TIMER_END';

export { TIMER_KICK_OFF, TIMER_TIME_OFF, TIMER_TIME_ON, TIMER_ADD_SECOND, TIMER_END }; 